catch: 
    const error = new CustomError(err.status, err.message)
        res.status(error.status).json({ status: error.status, error: error.message, data: null })
    
200:
    res.status(200).json({ status: 200, error: null, data:  })

Error:
    res.status().json({ status: , error: "", data: null })

201:
    res.status(201).json({ status: 201, error: null, data: "Successful Created" })
    